
source setenv.sh

#export LD_LIBRARY_PATH=lib/sgpp:hlrs-tools/boost_1_58_0/stage/lib/:$LD_LIBRARY_PATH
export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:$(pwd)/glpk/lib
echo $LIBRARY_PATH
scons -j 8 SG_ALL=0 SG_DISTRIBUTEDCOMBIGRID=1 VERBOSE=1 COMPILE_BOOST_TESTS=0 RUN_BOOST_TESTS=0 RUN_CPPLINT=0 BUILD_STATICLIB=0 CC=cc FC=ftn CXX=CC OPT=1 TIMING=1 LINKFLAGS="-lboost_serialization" LIBPATH=$BOOST_LIB BOOST_LIBRARY_PATH=$BOOST_ROOT/lib BOOST_INCLUDE_PATH=$BOOST_ROOT/include #DEBUG_OUTPUT=1

